[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["yarn install --frozen-lockfile", "npm install -g serve"]

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "serve -s build -l $PORT"
