[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install -g yarn", "yarn install --frozen-lockfile"]

[phases.build]
cmds = ["NODE_ENV=production bash build.sh"]

[start]
cmd = "node server.js"
