[phases.setup]
nixPkgs = ["nodejs_20", "bash"]

[phases.install]
cmds = [
    "npm install",
    "cd frontend && npm install"
]

[phases.build]
cmds = ["NODE_ENV=production npm run build"]

[start]
cmd = "node server.js"
